name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0

    - name: Install dependencies
      run: |
        gem install bundler:2.2.34
        bundle _2.2.34_ install --jobs 4 --retry 3
        npm install -g mermaid.cli

    - name: Enable bundler cache
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          echo "NO_PUSH=--no-push" >> $GITHUB_ENV
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. main, source etc
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        fi
        echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_ENV

    - name: Deploy website 
      run: |
        set -e # Exit on error
        yes | bash bin/deploy --verbose ${{ env.NO_PUSH }} \
          --src ${{ env.SRC_BRANCH }} \
          --deploy ${{ env.DEPLOY_BRANCH }}
